%HEATBYLIGHTSCRIPT Run all scenarios testing heating a greenhouse with light
% Script used to generate simulations in Chapter 5 of:
%   [1] Katzin, D. (2021). Energy saving by LED lighting in greenhouses: 
%       a process-based modelling approach (PhD thesis, Wageningen University).
%       https://doi.org/10.18174/544434

% David Katzin, Wageningen University
% david.katzin@wur.nl
% david.katzin1@gmail.com

%% 1. N: No lamps, no heat harvesting
runHeatByLightScenarios('lampType', 'none',...
        'heatHarvest', false, ... 
        'blackoutScreen', false, ...
        'boiler', true, ...
        'firstDay', 350, ...
        'saveFile', 'N');

%% 2. N HH: No lamps, with heat harvesting
runHeatByLightScenarios('lampType', 'none',...
        'heatHarvest', true, ... 
        'blackoutScreen', false, ...
        'boiler', true, ...
        'firstDay', 350, ...
        'saveFile', 'N-HH');

%% 3. L 200: LEDs at 200 µmol m^{-2} s^{-1}, with boiler and blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', true, ...
        'ppfd', 200, ...
        'saveFile', 'L-200');

%% 4. L 450: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450, ...
        'saveFile', 'L-450');

%% 5. L/L 450: Toplight/interlight LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450/2, ...
        'intPpfd', 450/2, ...
        'saveFile', 'LL-450');
    
%% 6. L 450 NBO: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, without blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', false, ...
        'boiler', false, ...
        'ppfd', 450, ...
        'saveFile', 'L-450-NBO');
    
%% 7. L 450 GL: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen, 
%              with a gradual response of lamp control to solar radiation
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450, ...
        'gradLamp', true, ...
        'saveFile', 'L-450-GL');
    
%% 8. L 450 20H: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen
%                with a maximum of 20 hours of lighting per day (instead of 18)
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450, ...
        'twentyHours', true, ...
        'saveFile', 'L-450-20H');
        
%% 9. L 450 BB: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen
%               with a bigger energy buffer
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450,...
        'paramNames', ["cBufSizeCold" "cBufSizeHot"], ...
        'paramVals', [1 2],...
        'saveFile', 'L-450-BB');
    
%% 10. L 450 SB: LEDs at 450 µmol m^{-2} s^{-1}, without boiler, with blackout screen
%               with a smaller energy buffer
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 450,...
        'paramNames', ["cBufSizeCold" "cBufSizeHot"], ... % Use values from Righini et al. (2020)
        'paramVals', [0.4184 0.8368],... % See Table 5.1 [1]
        'saveFile', 'L-450-SB');

%% 11. L 400: LEDs at 400 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 400, ...
        'saveFile', 'L-400');
    
%% 12. L 500: LEDs at 500 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'led', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 500, ...
        'saveFile', 'L-500');

%% 13. H/L 320: HPS toplight and LED interlights at 320 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'hps', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 200, ...
        'intPpfd', 120, ...
        'saveFile', 'HL-320');

%% 14. H/L 320 NBO: HPS toplight and LED interlights at 320 µmol m^{-2} s^{-1}, without boiler, without blackout screen
runHeatByLightScenarios('lampType', 'hps', ...
        'heatHarvest', true, ... 
        'blackoutScreen', false, ...
        'boiler', false, ...
        'ppfd', 200, ...
        'intPpfd', 120, ...
        'saveFile', 'HL-320-NBO');

%% 15. H/L 370: HPS toplight and LED interlights at 320 µmol m^{-2} s^{-1}, without boiler, with blackout screen
runHeatByLightScenarios('lampType', 'hps', ...
        'heatHarvest', true, ... 
        'blackoutScreen', true, ...
        'boiler', false, ...
        'ppfd', 200, ...
        'intPpfd', 170, ...
        'saveFile', 'HL-370');

%% 16. H/L 370 NBO: HPS toplight and LED interlights at 320 µmol m^{-2} s^{-1}, without boiler, without blackout screen
runHeatByLightScenarios('lampType', 'hps', ...
        'heatHarvest', true, ... 
        'blackoutScreen', false, ...
        'boiler', false, ...
        'ppfd', 200, ...
        'intPpfd', 170, ...
        'saveFile', 'HL-370-NBO');