"""
GreenLight/scripts/analyze_output.py
Copyright (c) 2025 David Katzin, Wageningen Research Foundation
SPDX-License-Identifier: BSD-3-Clause-Clear
https://github.com/davkat1/GreenLight

Functions for reformatting and analyzing outputs of the GreenLight platform
"""

import pandas as pd


def make_output_df(file_name) -> pd.DataFrame:
    """
    Load simulation result file, extract the variable names and the relevant data
    :param file_name: Location of CSV file generated by running GreenLight
    :return: pandas DataFrame containing the data, with columns named as the variable names
    """
    output_df = pd.read_csv(file_name, header=None, low_memory=False)
    variable_names = output_df.iloc[0]

    # Reformat the DataFrame with variable names as columns
    output_df = output_df.iloc[3:].reset_index(drop=True).apply(pd.to_numeric)
    output_df.columns = variable_names
    return output_df
